### ISSUE TITLE
Show IP address on a map

### ISSUE THREAD

**Issue by dt2i** [CyferShepard/Jellystat#117]
It might be an interesting feature to have a map that shows the locations for the ip addresses users are logging in from.

**Comment by DaftFuzz** [comment]
https://dev.maxmind.com/geoip/geolite2-free-geolocation-data allows 1000 requests per day to their API with a key, that's a pretty reasonable limit, plus I guess it could be an option to pass through your own keys via environment variables?

Their response looks like this: https://dev.maxmind.com/geoip/docs/web-services/responses#geoip2-city-body-example (the free API is less accurate, though)

I'm currently having a play at using this for something similar on a fork (specifically, being able to ad-hoc click the IP of a given session to show geodata for it), but it could easily be extended to build a map with the result coordinates 🤔 

What do you think?

**Comment by CyferShepard** [comment]
Hey @DaftFuzz , thanks for looking into this, i had looked into it once before but couldn't really find an api with a decent quantity of free requests. il look into using this one aswell as what other ones are available

**Comment by hadim** [comment]
In case it can help, I found a free geoip API: https://ip-api.com/

The limit is 45 requests per minute.
