### ISSUE TITLE
Feature request : exclude some users from stats

### ISSUE THREAD

**Issue by ValentinVie** [CyferShepard/Jellystat#118]
Hi ! First of all thanks for the work it's really cool to see an app like this for Jellyfin. The plug-in did not work as well. 

However a functionality I'm missing is the ability to exclude a user from stats. I usually troubleshoot and test content with  a specific Jellyfin account. I don't want to see that account increasing the stats as it is rather "fake" engagement with the content. 

Thanks in advance !
Cheers

**Comment by CyferShepard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [exclude some users from stats](https://trello.com/c/zumg12G6/12-exclude-some-users-from-stats)

**Comment by ValentinVie** [comment]
Thanks !
