### ISSUE TITLE
First Full Sync Failed, No Further Attempts

### ISSUE THREAD

**Issue by ghost** [CyferShepard/Jellystat#136]
**Describe the bug**
My first full sync failed to run after 0 seconds. I can't find any way to trigger it again, so only small syncs have happened and Jellystat thinks that I have only 10 movies and 1 TV show...

**Environment Details (please complete the following information):**
 - OS: Docker
 - Browser: N/A
 - Jellystat Version: 1.0.9
 - Jellyfin Version: 10.8.13

**To Reproduce**
1. Have bad luck and the initial full sync fails to run?

**Expected behavior**
Full sync is attempted again or I can manually trigger it.

**Screenshots**
![logs](https://github.com/CyferShepard/Jellystat/assets/113205165/c62b2f18-25c0-4d35-8293-0005605933aa)

![libs](https://github.com/CyferShepard/Jellystat/assets/113205165/deb09c42-51aa-4eff-a65a-87d1cb83d1b0)

**Task Logs**
See above.

**Container Logs**
Nothing relevant captured at the time.

**Additional context**
N/A

**Comment by CyferShepard** [comment]
Hey @wkeiuluf , do you mind sharing the logs for that task? If you clock the + icon next to the task, it should expand and show you the logs

**Comment by CyferShepard** [comment]
sorry i missed that screenshot
so it looks like it couldn't connect to jellyfin when it did the first attempt. Manually running the full sync should fix it, il check why it didnt reattempt it as its meant to reattempt the sync after 15 minutes

**Comment by CyferShepard** [comment]
so under settings, the very first tab, scroll to the bottom
