### ISSUE TITLE
Jellystat shuts down during first setup

### ISSUE THREAD

**Issue by zehDonut** [CyferShepard/Jellystat#137]
**Describe the bug**
When I start the jellystat container for the first time, it shuts down after a few seconds.
[first_start.log](https://github.com/CyferShepard/Jellystat/files/13627880/first_start.log)

Starting the container a second time works until I setup a user & server during the initial setup. Now I get the following errors.
(The TypeError section then keeps looping indefinitely)
[second_start.log](https://github.com/CyferShepard/Jellystat/files/13627886/second_start.log)

It's still possible to navigate the web interface afterwards.

**Environment Details (please complete the following information):**
 - OS: Debian 12 Kernel 6.1.0-13-amd64
 - Browser doesn't apply
 - Jellystat Version 1.0.9
 - Jellyfin Version 10.8.13

**Comment by CyferShepard** [comment]
Hey @zehDonut , can you do me a favor and attempt to re-enter and save your jellyfin details under settings, once saved can you restart it and let me know if the error still persists?

**Comment by zehDonut** [comment]
Hi,

unfortunately that didn't fix the problem, the behavior is still the same after saving + restarting.

**Comment by CyferShepard** [comment]
Hey @zehDonut , can you pull the latest image and test again

**Comment by zehDonut** [comment]
That seems to have fixed the TypeError messages.

I've discovered that I need to enable remote access in Jellyfin (even though both containers are in the same docker network). Now most things work, except the "Libraries" section, which is empty. (And by extension opening any library item, e.g. in recently added)

[log1.log](https://github.com/CyferShepard/Jellystat/files/13628862/log1.log)

**Comment by CyferShepard** [comment]
can you retry running a full sync and let me know?

**Comment by zehDonut** [comment]
I was just about to edit my message, I did another restart and everything works now.
Thank you very much for your help!
