### ISSUE TITLE
Statistics graph visualizations go below 0

### ISSUE THREAD

**Issue by cm-chandler** [CyferShepard/Jellystat#14]
![jstat](https://user-images.githubusercontent.com/81978586/231024312-98a88144-effd-4c0d-894b-5e51e1f6ed3d.png)

Data points that equal 0 which proceed or follow >0 data points will be visualized below 0.

**Comment by CyferShepard** [comment]
Hi @cm-chandler , this is due to how this library tries to draw graphs with a natural curve. I'm currently looking into new libraries to fix this this. Will leave this issue open and close it off when it's replaced.

**Comment by CyferShepard** [comment]
This has been fixed why changing graph libraries and will be merged to main soon.
