### ISSUE TITLE
Database Name

### ISSUE THREAD

**Issue by MrMarble** [CyferShepard/Jellystat#152]
Environment variable `POSTGRES_DATABASE` is only used in backup https://github.com/CyferShepard/Jellystat/blob/ccc4cef70d5bee9cd1c339c23a68f42f7f1a7ca9/backend/routes/backup.js#L25 and ignored on the rest of the code making the variable useless:

https://github.com/CyferShepard/Jellystat/blob/ccc4cef70d5bee9cd1c339c23a68f42f7f1a7ca9/backend/db.js#L24
https://github.com/CyferShepard/Jellystat/blob/ccc4cef70d5bee9cd1c339c23a68f42f7f1a7ca9/backend/migrations.js#L10
https://github.com/CyferShepard/Jellystat/blob/ccc4cef70d5bee9cd1c339c23a68f42f7f1a7ca9/backend/create_database.js#L18

**Comment by jsmouret** [comment]
+1 as it blocks having multiple instances plugged on the same database server
