### ISSUE TITLE
What is JWT Secret

### ISSUE THREAD

**Issue by lightmaster** [CyferShepard/Jellystat#162]
**Describe the bug**
Probably not a bug, just my ignorance. I've searched through the Issues on here, but I'm unable to figure out what the "JWT Secret" is supposed to be.

**Environment Details (please complete the following information):**
 - OS: Debian 12
 - Browser: Firefox
 - Jellystat Version: Whatever the current docker image is. Can't start it so don't know what it is
 - Jellyfin Version: 10.8.13

**Comment by CyferShepard** [comment]
Hey @lightmaster ,

A JWT secret is a special online code that acts like a secret handshake for computer systems to trust each other. This code can be generated using online tools and typically consists of a random mix of letters and numbers. A recommended JWT secret is a complex and unique combination, similar to a strong, hard-to-guess password, to enhance security. Eg `MySuperSecretJWT01`
