### ISSUE TITLE
This is not an issue can this be installed on raspberrypi 4?

### ISSUE THREAD

**Issue by Kev1n121** [CyferShepard/Jellystat#169]
This is not an issue can this be installed on raspberrypi 4? I cant find any infomation on the net about this.

**Comment by CyferShepard** [comment]
Hey @Kev1n121 , no not yet, while there is an image available for arm platforms, its abit buggy, it works fine for some people and for others they get issue with either the setup process or with syncing

**Comment by Kev1n121** [comment]
Hey @CyferShepard, oh ok hope it will be available asap:) Thank you for your reply. Most of times I add issues on Github I never been replyed. Thank for your work you put in this project.

**Comment by CyferShepard** [comment]
so take a look at the docker hub page here  [cyfershepard/jellystat](https://hub.docker.com/repository/docker/cyfershepard/jellystat), you can copy the contents of the file and paste it in a new file called docker-compose.yml, then in the same directory run `docker-compose up -d`

**Comment by Kev1n121** [comment]
thank you I did that, Now I getting : 
v@raspberrypi:~/Jellystat $ docker-compose up -d
[+] Running 22/22
 ⠿ jellystat Pulled                                                                                                                                     263.0s
   ⠿ 24e221e92a36 Pull complete                                                                                                                          11.8s
   ⠿ dbc596c5cca5 Pull complete                                                                                                                          12.0s
   ⠿ 5968e8f9aaaa Pull complete                                                                                                                          85.1s
   ⠿ 7e9262df0e0d Pull complete                                                                                                                          85.7s
   ⠿ fc981e182978 Pull complete                                                                                                                          86.0s
   ⠿ 8a5293ae2219 Pull complete                                                                                                                          86.3s
   ⠿ c146f0795bb5 Pull complete                                                                                                                         260.3s
 ⠿ jellystat-db Pulled                                                                                                                                  139.2s
   ⠿ b5d25b35c1db Pull complete                                                                                                                          85.0s
   ⠿ 49cf892a3d6e Pull complete                                                                                                                          85.3s
   ⠿ 2a0b6c31bad8 Pull complete                                                                                                                          86.0s
   ⠿ 30c88dd7faee Pull complete                                                                                                                          86.6s
   ⠿ 8ed188c9a01e Pull complete                                                                                                                          88.4s
   ⠿ 5ef46eb6901b Pull complete                                                                                                                          88.9s
   ⠿ 691a93171f6d Pull complete                                                                                                                          89.0s
   ⠿ f492dbf99c64 Pull complete                                                                                                                          89.1s
   ⠿ 30f9a70969b5 Pull complete                                                                                                                         135.7s
   ⠿ c20fc1dde117 Pull complete                                                                                                                         135.9s
   ⠿ 9930c16ee27c Pull complete                                                                                                                         136.0s
   ⠿ 149a29989f91 Pull complete                                                                                                                         136.1s
   ⠿ 9282b944f2c9 Pull complete                                                                                                                         136.2s
[+] Running 3/3
 ⠿ Network jellystat_default           Created                                                                                                            0.7s
 ⠿ Container jellystat-jellystat-db-1  Started                                                                                                            4.1s
 ⠿ Container jellystat-jellystat-1     Started 

but now I going to jellyfin(IP):5432 but its Unable to connect. Do I need to do something more?

**Comment by Kev1n121** [comment]
Also Is there a way to start the docker container on boot? so I dont have to add command all the time to load the docker,
