### ISSUE TITLE
Error : Unable to connect to Jellyfin Server

### ISSUE THREAD

**Issue by ftc2** [CyferShepard/Jellystat#17]
hi. there is definitely a need for a project like this, so thanks for tackling it. i hope this gains traction, matures, and becomes **the** solution for jellyfin usage stats and monitoring.

problem:

for server url, i'm trying `http://jellyfin` and `http://jellyfin:8096` (the same url my reverse proxy hits on the backend) where `jellyfin` is my jellyfin container name. i can successfully `curl -L http://jellyfin:8096` from inside the jellystat container, so i don't really get it.

it says: `Error : Unable to connect to Jellyfin Server`

for now, i'm doing `https://jellyfin.example.com` (my exposed endpoint), but it would make a lot more sense to do backend communication over a private docker network.

ideas?

**Comment by CyferShepard** [comment]
Hi @ftc2 , thanks, I noticed that it's been a while since jellyfin gained traction but no one decided to create a stats report like this, so I decided to take Matters into my very inexperienced hands, I do hope it gains traction and others decide to pitch in aswell, for now Il try my best.

 It could be the way axios tries to resolves the DNS lookup, I'm not quite sure and will have to test but thanks for bringing this up. My JF instance is not running inside docker and I would have never picked up an issue like this.

**Comment by ftc2** [comment]
https://github.com/CyferShepard/Jellystat/blob/10983421a093f04117014f7c480914c2606bf513/src/pages/setup.js#L46

https://github.com/axios/axios/issues/1418#issuecomment-373386206

maybe?

btw, i've never used node before. what's the easiest way to debug? can i get an interactive environment somehow and play with commands like `axios.get()`?

**Comment by ftc2** [comment]
no, i'm suggesting that `jest` could be messing it up

**Comment by ftc2** [comment]
@CyferShepard just tested, lgtm

thanks

**Comment by megavenik** [comment]
hi, @CyferShepard ! Sorry to disturb you, but I'm also experiencing the mentioned issue.

Connection from inside of the jellystat container works as expected:

```
root@27c433300b88:/app# curl -H "X-MediaBrowser-Token: 9158c9********************81111e8c3" -H "Content-Type: application/json" 192.168.0.59:8096/system/configuration
{"EnableMetrics":false,"EnableNormalizedItemByNameIds":true,"IsPortAuthorized":true,"QuickConnectAvailable":true,"EnableCaseSensitiveItemIds":true,"DisableLiveTvChannelUserDataName":true,"MetadataPath":"","MetadataNetworkPath":"","PreferredMetadataLanguage":"ru","MetadataCountryCode":"RU", ... blah-blah-blah a very long json ...
27c433300b88:/app#
```
but in the browser and logs I'm getting:

```
jellystat-jellystat-1     | [JELLYSTAT] Server listening on http://127.0.0.1:3000
jellystat-jellystat-1     | Activity Interval: 1000
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | {
jellystat-jellystat-1     |   isValid: false,
jellystat-jellystat-1     |   errorMessage: 'Error : Unable to connect to Jellyfin Server'
jellystat-jellystat-1     | }
```

Can you help with this please?

**Comment by CyferShepard** [comment]
Hi @megavenik, can you show me the url your trying to set? this error message comes up when its unable to connect via the provided URL

**Comment by CyferShepard** [comment]
can you try with http:// in the front so itl be http://192.168.0.59:8096

**Comment by megavenik** [comment]
yeah, this one helped) thanks!
