### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by Schaka** [CyferShepard/Jellystat#170]
I'm working on a [Janitorr ](https://github.com/Schaka/janitorr)app, similar to [Maintainerr](https://github.com/jorenn92/Maintainerr). One of the most requested features is having Jellystat integration, so that media that may be really old but still gets accessed frequently won't be deleted. The Playback Reporting Plugin may work but I think I would prefer Jellystat overall, as it's much easier to integrate another app rather than relying ont he user to install a plugin which doesn't supply stats in the way I would need anyway.

Here's the problem: It doesn't look like there are any API docs yet. Is there any way you could auto generate some OpenAPI docs or similar? 

I don't need in-depth explanation for everything, but I'd love to know what my options are without reverse engineering all the requests I see my browser make.

**Comment by CyferShepard** [comment]
Hey @Schaka , api docs are available, you can find them at https://example.jellystat.server./swagger. If you need any other information or clarification, feel free to reach out
