### ISSUE TITLE
Fresh docker install can't get connected to jellyfin

### ISSUE THREAD

**Issue by Glynax** [CyferShepard/Jellystat#173]
**Describe the bug**

**Environment Details (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome, Mozilla]
 - Jellystat Version [1.0.9]
 - Jellyfin Version [e.g. 10.8.13]

**To Reproduce**
I followed the docker compose and started the containers, I can make a user and log in but I can't seem to get any variation of my local IP http://192.168.1.134:8096/jellyfin/ to work and start scanning in things and detect streams.

**Expected behavior**
I expected to be able to connect to jellyfin, I may just be having a brain fart on the connection but so far I've ensured my firewall isn't blocking it and I've tried my nginx reverse proxy URL I've tried the local IP, in several variations and none of them connect even if it seems to accept it.

**Screenshots**

**Task Logs**
If applicable, add Task Logs for your problem.

**Container Logs**
If applicable, add Container Logs for your problem.
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }

**Additional context**
here's my compose

version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *****
    volumes:
    - /opt/jellystat/postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: *****
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3000:3000" #Server Port
    volumes:
      - /opt/jellystat/backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
    restart: unless-stopped
networks:
  default:

**Comment by CyferShepard** [comment]
Hey @Glynax , the URL for jellyfin you provided looks incorrect, the standard url for a jellyfin instance is `[http/https]://[IP_ADDRESS]:[PORT]`, in your case, can you try `http://192.168.1.134:8096` without jellyfin in the end

**Comment by Glynax** [comment]
That got me working, so sorry to waste your time with something so simple I just could not get this working last night.
