### ISSUE TITLE
New jellyfin user not showing in user list

### ISSUE THREAD

**Issue by Darkmagister** [CyferShepard/Jellystat#179]
**Describe the bug**
i've created a new user in jellyfin but it does not appear in jellystat user page, i can see in the homepage the sessions of that user with it's name but if i go in users page or click on the user name it doesn't show anything how can i force a resync i've tried with the button in the setting page but still this situation, also no info in the stats and so on.

**Environment Details (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Jellystat Version 1.0.9
 - Jellyfin Version 10.8.13

**To Reproduce**
1. add new user in jellyfin
2. run sync in jellystat (or wait for the scheduled run)
3. go to users page
4. the new user is not there

**Expected behavior**
i would like to see the new users in jellystat

**Additional context**
i have to remove manually restart jellystat (it run in docker) and then it will show the new user (if i just stop docker doens't work, i need to stop the container e restart it)

**Comment by CyferShepard** [comment]
Hi, have you tried refreshing the page instead of restarting the container? It sounds to me like a caching issue and just a simple refresh of the page will show the new data. Can you try that and let me know?

**Comment by Darkmagister** [comment]
yes it was a cache problem, very strange that only in that page i need to force update the page to see the new users, thanks and sorry for this.
