### ISSUE TITLE
Feature Request: base url

### ISSUE THREAD

**Issue by ftc2** [CyferShepard/Jellystat#18]
be able to set a base url (sub path) so that you can host at, for example:

`https://example.com/jellystat`
instead of
`https://jellystat.example.com`

ideally, let this be set by an env var like:
`BASE_PATH=foo`
yielding responses at:
`$scheme:$domain/foo`

**Comment by CyferShepard** [comment]
Hi @ftc2 , can you perhaps share a sample config and what reverse proxy you are using? I'm not sure how this would affect accessibility. If I can replicate it maybe I can develop a work around.

 What error do you get when accessing the URL based on a this configuration aswell.

**Comment by ftc2** [comment]
i haven't actually tested it, i just assumed it wouldn't work. i've had very bad luck with projects using node frameworks supporting this feature.

will confirm it doesn't "just work" later today and share a sample config :)

**Comment by CyferShepard** [comment]
Hi @ftc2, sorry i completely missed this comment, yes please do, i will test and see if i can replicate the behavior you described

**Comment by ftc2** [comment]
@CyferShepard 

no worries, here you go. made you this to play with:

https://github.com/ftc2/jellystat-nginx

includes production-ish settings for postgres in the docker compose.

in the nginx config, i show you two common options for subpath aka basepath config. i am not optimistic, though. in my limited experience with node framework type projects, if basepath is supported at all, it's not supported as something that can be set at runtime lol. idk what the deal is.

something i wanted to point out 'early' though because it's a very frequently requested feature in the automated media app ecosystem.

**Comment by CyferShepard** [comment]
So I managed to replicate the issue. This is really one confusing scenario, thanks for pointing it out but. I did some research and I'm so happy this was pointed out so early in development as the fix for it seems to be very time consuming as il need to rework some of the api endpoints in the react part of things.

**Comment by Opa-** [comment]
Would be awesome to have that feature, I'd want to run my jellystat intance behind an nginx proxy at `http://<domain>.io/stats/`
