### ISSUE TITLE
Very slow and failed "full jellyfin sync" + slow UI and container errors

### ISSUE THREAD

**Issue by simon96aic** [CyferShepard/Jellystat#186]
**Describe the bug**
When I create a new instance and import data from "Playback Reporting Plugin" and do a full jellyfin sync. Many errors appear in the log and the full sync is very slow (~45min). UI doesn't really respond at all.

**Environment Details (please complete the following information):**
 - OS: docker
 - Browser: all 
 - Jellystat Version 1.0.9
 - Jellyfin Version 10.8.13

**To Reproduce**
1. Run fully jellyfin sync
2. Go to container logs, see errors.
3. See error in UI in the full jellyfin sync logs

**Expected behavior**
No errors and not slow

**Container Logs**
Error {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
  Message: 'connect EHOSTUNREACH 181.132.132.132:443'
}
...
[JELLYFIN-API]: Unexpected status code: 504
[JELLYFIN-API]: Unexpected status code: 504
[JELLYFIN-API]: Unexpected status code: 504
...
TypeError: error.message.contains is not a function
    at Object.query (/app/backend/db.js:159:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout._onTimeout (/app/backend/tasks/ActivityMonitor.js:32:26)

**Additional context**
nginx proxy manager used

**Images:**
![image](https://github.com/CyferShepard/Jellystat/assets/6340498/3d344c03-6b2c-4046-a8b7-6bdde9611710)

**Comment by CyferShepard** [comment]
hey @simon96aic , can you try using the `unstable` build? most of the bugs have been fixed and this will be making its way to stable soon. Also the errors seem like your jellyfin instance timed out. Error 504 means `A 504 Gateway Timeout error indicates that the web server is waiting too long to respond from another server and “timing out."`

**Comment by simon96aic** [comment]
Unstable build is working.
Thank you. 👍
