### ISSUE TITLE
Additional Info on Activity Grid

### ISSUE THREAD

**Issue by ShakeSp33r** [CyferShepard/Jellystat#190]
**Is your feature request related to a problem? Please describe.**
On the activity grid, if possible to the **DeviceName** & **Playmethod** fields for jf_playback_activity.

This is just nice to have info.

**Comment by CyferShepard** [comment]
So i added device name, its building at the moment, can you click on the client, there should be a popup with playmethod. It would be nice to have it on the main table and not in a submenu but then the table starts to grow past the screen size and you'd need to scroll which i find to be a hassle if you need to view data

**Comment by ShakeSp33r** [comment]
Working perfectly.
