### ISSUE TITLE
0 second plays in Activity

### ISSUE THREAD

**Issue by ForbiddenOne** [CyferShepard/Jellystat#199]
**Describe the bug**
The activity is full of "plays" with playback time 0 seconds. This happens because the user left the jellyfin player open. It would be nice to have them removed because the graphs for the statistics get completely messed up

**Environment Details (please complete the following information):**
 - OS: Linux Docker
 - Browser: Mozilla
 - Jellystat Version: 1.0.9
 - Jellyfin Version [e.g. 10.8.13

![imagem](https://github.com/CyferShepard/Jellystat/assets/36516219/eaac8f7c-845a-4201-938a-807cb3c3b7c6)

**Comment by CyferShepard** [comment]
Hey @ForbiddenOne , this has been fixed in `unstable`, it will make its way to the `stable` branch once im done with a few other bugs

**Comment by ForbiddenOne** [comment]
Great! Thank you for the reply!
