### ISSUE TITLE
Changing intervals under Tasks in Settings doesn't update the UI until changing tabs

### ISSUE THREAD

**Issue by BRTPOB** [CyferShepard/Jellystat#207]
**Describe the bug**
When a user is on the Settings tab of Jellystat, and they change the interval for a Task, the UI will not update showing the new change until after the user clicks on another tab to take them away from the Settings page, and then back again.

**Environment Details (please complete the following information):**
 - OS: Ubuntu
 - Browser Edge
 - Jellystat Version: 1.1.0
 - Jellyfin Version: 10.9.2

**To Reproduce**
1. Go to Settings
2. Click on a different interval for tasks
3. Notice the task interval doesn'y update

**Expected behavior**
Expected Tasks intervals to update like the other dropdowns on the page.

**Screenshots**
N/A

**Task Logs**
N/A

**Container Logs**
N/A

**Additional context**
I'm using the nightly/unstable docker container version.

**Comment by CyferShepard** [comment]
Hi, this has been fixed as per 1.1.0
