### ISSUE TITLE
Many playbacks with 0-1 seconds of activity

### ISSUE THREAD

**Issue by zodac** [CyferShepard/Jellystat#208]
**Is your feature request related to a problem? Please describe.**
I am setting up Jellystat for the first time with my Emby server, and I'm seeing many instances of tiny playbacks of 0-1 seconds in length:

![image](https://github.com/CyferShepard/Jellystat/assets/2502611/1baaaab2-3132-418a-aa83-b11a9e37a800)

I'm not sure why it's coming into Jellystat with this data, my reporting on the Emby server shows a reasonable play count (though it's possible that reporting is doing some combination/filtering already).

**Describe the solution you'd like**
Would it be possible to have a user-configurable setting for a 'minimum length' in seconds for a playback to be considered a valid activity?

**Describe alternatives you've considered**
Potentially each entry under a length is combined, so 10 playbacks of 2 seconds would instead be 1 playback of 20 seconds? But I personally would prefer just excluding things under a specified length.

**Additional context**
**Environment Details:**
 - OS: Docker
 - Browser: Chrome
 - Jellystat Version: v1.0.9
 - Emby Version: Emby v4.8.7.0

**Comment by CyferShepard** [comment]
Hey @zodac , this has been fixed in v 1.1.0, which is currently on the unstable branch, your free to use it  as its actually pretty stable and ready for release, just a few bugs that already exist in 1.0.9 that have not been fixed that are holding it back

**Comment by zodac** [comment]
That's good to know, thanks! I'll try out the unstable image and give it a shot. :)
