### ISSUE TITLE
unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown 

### ISSUE THREAD

**Issue by lockheed** [CyferShepard/Jellystat#209]
I cannot deploy jellystat in docker in any of the available images. Deployment ends with:

`Failed to deploy a stack: jellystat.pl Pulling jellystat.pl Pulled Network jellystat.pl Creating Network jellystat.pl Created Container jellystat.pl-db Creating Container jellystat.pl-db Created Container jellystat.pl Creating Container jellystat.pl Created Container jellystat.pl-db Starting Container jellystat.pl-db Started Container jellystat.pl Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown `

I tried docker prune, deleting images, nothing helped.

**Environment Details (please complete the following information):**
 - OS: Arch
 - Browser Firefo
 - Jellystat Version: latest, 1.0.9
 - Jellyfin Version 10.9.1

**Comment by CyferShepard** [comment]
Hey @lockheed , this looks like a docker issue, a quick google search lead me to this. ["exec: \"docker-entrypoint.sh\": executable file not found in $PATH"](https://github.com/docker-library/postgres/issues/296) Hope it helps.

**Comment by lockheed** [comment]
@CyferShepard 
docker-entrypoint.sh is the entrypoint script for the docker image. I think it should be provided by the image itself.

**Comment by CyferShepard** [comment]
Hey @lockheed , yea i just realized, it should be fixed now
can you check now?

**Comment by lockheed** [comment]
It worked. Thanks for the fix!
