### ISSUE TITLE
Several architectures missing in docker image tagged 1.1.0

### ISSUE THREAD

**Issue by Intuinewin** [CyferShepard/Jellystat#216]
**Describe the bug**

For the `1.1.0` tag, only the `linux/arm/v7` image seems to have been pushed to docker hub (https://hub.docker.com/r/cyfershepard/jellystat/tags). Could you push the other 2 arch: `linux/amd64, linux/arm64` ?

**Comment by CyferShepard** [comment]
Hey @Intuinewin , Yea im currently working on this, been having issues building the containers so theres abit of a delay on, hoping to get it up in the next few hours

**Comment by CyferShepard** [comment]
This has be fixed now

**Comment by Intuinewin** [comment]
Works like a charm, thank you
