### ISSUE TITLE
Improvements to Recently Added

### ISSUE THREAD

**Issue by crazybadger** [CyferShepard/Jellystat#228]
I still haven't worked out exactly what is being shown under Recently Added on the Home Page, but can it be restricted in the same way I can switch Libraries on/off to be displayed?  Thanks

**Comment by JamsRepos** [comment]
It shows the exact same recently added as Jellyfin does.

**Comment by CyferShepard** [comment]
Hey @crazybadger , just to clarify, you want the Recently added on the home page to filter out items from libraries you marked as untracked?

**Comment by crazybadger** [comment]
Thanks for the replies!  I'm using this with emby and that doesn't have a 'Recently added' as such, but I assuming this is picking up all of the 'Latest ...' sections?  I'm only interested in my TV, Movies and Music libraries so have switched off the others (in the Settings > Library Settings) but 'Recently Added' is picking up other things like TuneIn and Trailers that I'd prefer not to see.  Some user control over these would be great.  

It's working well though after installing just over a week ago, so thanks for all your efforts.  The best plexpy replacement I've used so far for emby/jellyfin.
