### ISSUE TITLE
Concurrent streams value incorrect on home page 

### ISSUE THREAD

**Issue by ShakeSp33r** [CyferShepard/Jellystat#231]
**Describe the bug**
The concurrent streams values on the home page are incorrect. 

**Environment Details (please complete the following information):**
 - OS: Debian
 - Browser : Any
 - Jellystat Version : Ver 1.1.1
 - Jellyfin Version : 10.9.8

**To Reproduce**
Change the Watch Statistics Last Days to 1 and it show 10 even though nothing is in the active list. 
Change it to 2 and it show 43 even though only 10 Movies/Episodes were watched.
Change it to 3 and it show 72 even though only 43 Movies/Episodes were watched.
Seems like the rest of the info show data since 00h00 and Concurrent Streams show for the last x*24 hours.

**Expected behavior**
Concurrent streams should use the same time interval as the rest.

**Screenshots**
![Last 1 Day](https://github.com/user-attachments/assets/99311f28-4003-42a6-a2d5-bd16ac5941c3)
![Last 2 Days](https://github.com/user-attachments/assets/199414d9-0e9b-413a-81f9-7e61590f35fb)

**Comment by CyferShepard** [comment]
Hey @ShakeSp33r , can you do me a favor and show me the api calls under the browser dev tools > network tab. Like Below
![image](https://github.com/user-attachments/assets/7ee9f1f0-a5cc-414e-8a9a-2857a1afdca2)
Specifically the Payload and Response message for each usecase provided. The code currently applies the same time range logic as the other stats. im trying to see if maybe this is a visual bug where you make the change but it only refreshes the page and displays the fetched data from the last change

**Comment by ShakeSp33r** [comment]
This is the totals for total
![Screenshot 2024-08-03 at 19 43 27](https://github.com/user-attachments/assets/c2622a72-ae69-4b4b-ae4e-66a5ff2ed7ca)

Your request as above
![Screenshot 2024-08-03 at 19 42 44](https://github.com/user-attachments/assets/ed75de5b-e9d0-4e90-8726-f3980db0eaeb)
![Screenshot 2024-08-03 at 19 42 29](https://github.com/user-attachments/assets/7e9d6e46-fa98-4f82-9201-e662884e192b)

**Comment by CyferShepard** [comment]
Found the issue, i was doing a date offset by -1 further down in the other views which i didnt see
