### ISSUE TITLE
Playback Time includes time paused

### ISSUE THREAD

**Issue by ShakeSp33r** [CyferShepard/Jellystat#234]
**Describe the bug**
When playing a video in chrome, and pausing it, the total playback time recorded is the normal time played + the time paused.

**Environment Details (please complete the following information):**
 - OS: Debian
 - Browser: Chrome
 - Jellystat Version: v1.1.1 (Unstable 4 Sep 2024)
 - Jellyfin Version: 10.9.9

**To Reproduce**
1. Play any media on Jellyfin in chrome.
2. Pause the video for x minutes
3. Continue watching
4. Total playback time include the time it was paused.
(Have not yet tested this using Android TV)

**Expected behavior**
Should only record the total play time (excluding and time paused)

**Comment by CyferShepard** [comment]
Hey @ShakeSp33r , is this only in Chrome or is it happening regardless of the watch client?

**Comment by ShakeSp33r** [comment]
@CyferShepard 
Will do a couple of tests in various clients and get back to you

**Comment by ShakeSp33r** [comment]
@CyferShepard 
I've tested Firefox, Safari and Android TV 17.1 also. All doing the same thing, however it's a bit strange, if you play the media and pause it for a short time less than 5 min, and then continue, it records the correctly. I had it pause for 23min and included the paused time also.

**Comment by CyferShepard** [comment]
Hmmm, Thats strange, il try to replicate when i get time this weekend
