### ISSUE TITLE
Can’t update Jellyfin URL and API values in Settings ?

### ISSUE THREAD

**Issue by nodecentral** [CyferShepard/Jellystat#248]
**Describe the bug**

Changes being made to the settings are not being saved, even though Update has been pressed (and occasional a save successfully message comes up)

**Environment Details (please complete the following information):**
 - OS: QNAP - Docker 
 - Browser [e.g. chrome, Mozilla] - iOS Safari
 - Jellystat Version [e.g. 1.0.0] 1.1.0
 - Jellyfin Version [e.g. 10.0.5] 10.9.9

**To Reproduce**
1. Go to '.Settings update Jellyfin URL and API Key'
2. Click on 'Update.' 
3. Refresh the browser '
4. Settings are not changed

**Expected behavior**
Settings should be saved

**Screenshots**
<img width="648" alt="image" src="https://github.com/user-attachments/assets/e13e765a-3171-46ed-bd53-552eee2aa17b">

**Task Logs**
````
http://192.168.102.134:8096/ true
http://192.168.102.134:8096/ true
http://192.168.102.134:8096/ true
http://192.168.102.134:8096/ true
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:118:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:118:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:146:23'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
````

**Comment by nodecentral** [comment]
Hi @CyferShepard - do you need anything more from me on this issue ?

Is there anything I can do in the interim ?  The Jellyfin ip and port, it gave me is the one I set up for jelly stat, and no matter what I can do I can’t edit it. Is there somewhere like a config/txt/xml file where I could maybe edit it in ?

**Comment by CyferShepard** [comment]
Hey @nodecentral , can you pull the newest unstable image and try again? i added safety checks for the code where the logs indicated an error. I just want to see if that helps or if theres a new error

**Comment by nodecentral** [comment]
Hi - OK - pulled the unstable version and tried to make changes to the Jelly fin URL and API key again..

No message comes up, and upon refresh the it returns to it’s original value - so the problem still occurs.. Here is a snap of the log..
````
&gt; jfstat@1.1.1 start
&gt; cd backend &amp;&amp; node server.js
all values are hidden
env.js file has been saved successfully.
[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000/
&lt;!DOCTYPE html&gt;
&lt;html lang=&#34;en&#34;&gt;
  &lt;head&gt;
    &lt;meta charset=&#34;UTF-8&#34; /&gt;
    &lt;link rel=&#34;icon&#34; href=&#34;favicon.ico&#34; /&gt;
    &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1.0&#34; /&gt;
    &lt;meta name=&#34;theme-color&#34; content=&#34;#000000&#34; /&gt;
    &lt;meta name=&#34;description&#34; content=&#34;Jellyfin stats for the masses&#34; /&gt;
    &lt;link rel=&#34;apple-touch-icon&#34; href=&#34;icon-b-192.png&#34; /&gt;
    &lt;script src=&#34;env.js&#34;&gt;&lt;/script&gt;
    &lt;!--
      manifest.json provides metadata used when your web app is installed on a
      user&#39;s mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    --&gt;
    &lt;link rel=&#34;manifest&#34; href=&#34;manifest.json&#34; /&gt;
    &lt;!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.
all values are hidden
      Unlike &#34;favicon.ico&#34; or &#34;favicon.ico&#34;, &#34;%PUBLIC_URL%/favicon.ico&#34; will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    --&gt;
    &lt;title&gt;JellyStat&lt;/title&gt;
    &lt;script type=&#34;module&#34; crossorigin src=&#34;./assets/index-864c1f9d.js&#34;&gt;&lt;/script&gt;
    &lt;link rel=&#34;modulepreload&#34; crossorigin href=&#34;./assets/vendor-2d4d1dd6.js&#34;&gt;
    &lt;link rel=&#34;stylesheet&#34; href=&#34;./assets/index-ac22111c.css&#34;&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;noscript&gt;You need to enable JavaScript to run this app.&lt;/noscript&gt;
    &lt;div id=&#34;root&#34;&gt;&lt;/div&gt;
    
  &lt;/body&gt;
&lt;/html&gt;
all values are hidden
[JELLYFIN-API] {
  ErrorAt: &#39;at JellyfinAPI.getRecentlyAdded (/app/backend/classes/jellyfin-api.js:355:48&#39;,
  ErrorLines: [
    {
      TraceIndex: 1,
      line: &#39;/app/backend/classes/jellyfin-api.js:355:48&#39;
    },
    { TraceIndex: 2, line: &#39;node:internal/process/task_queues:105:5&#39; },
    {
      TraceIndex: 3,
      line: &#39;at async /app/backend/routes/api.js:170:38&#39;
    }
  ],
  Message: &#34;Cannot read properties of undefined (reading &#39;Id&#39;)&#34;,
  url: undefined
}
&lt;!DOCTYPE html&gt;
&lt;html lang=&#34;en&#34;&gt;
  &lt;head&gt;
    &lt;meta charset=&#34;UTF-8&#34; /&gt;
    &lt;link rel=&#34;icon&#34; href=&#34;favicon.ico&#34; /&gt;
    &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1.0&#34; /&gt;
    &lt;meta name=&#34;theme-color&#34; content=&#34;#000000&#34; /&gt;
    &lt;meta name=&#34;description&#34; content=&#34;Jellyfin stats for the masses&#34; /&gt;
    &lt;link rel=&#34;apple-touch-icon&#34; href=&#34;icon-b-192.png&#34; /&gt;
    &lt;script src=&#34;env.js&#34;&gt;&lt;/script&gt;
    &lt;!--
      manifest.json provides metadata used when your web app is installed on a
      user&#39;s mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    --&gt;
    &lt;link rel=&#34;manifest&#34; href=&#34;manifest.json&#34; /&gt;
    &lt;!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.
all values are hidden
      Unlike &#34;favicon.ico&#34; or &#34;favicon.ico&#34;, &#34;%PUBLIC_URL%/favicon.ico&#34; will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    --&gt;
    &lt;title&gt;JellyStat&lt;/title&gt;
    &lt;script type=&#34;module&#34; crossorigin src=&#34;./assets/index-864c1f9d.js&#34;&gt;&lt;/script&gt;
    &lt;link rel=&#34;modulepreload&#34; crossorigin href=&#34;./assets/vendor-2d4d1dd6.js&#34;&gt;
    &lt;link rel=&#34;stylesheet&#34; href=&#34;./assets/index-ac22111c.css&#34;&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;noscript&gt;You need to enable JavaScript to run this app.&lt;/noscript&gt;
    &lt;div id=&#34;root&#34;&gt;&lt;/div&gt;
    
  &lt;/body&gt;
&lt;/html&gt;
all values are hidden
http://192.168.102.134:8096/ true
````

**Comment by nodecentral** [comment]
Just to share the sequence..

After I make the change to the Jellyfin URL and API key I hit Update, and the log shows the following..
````
http://192.168.102.134:8096/ true
````
From there, I then hit refresh of the browser to see if it has saved, and then it gives me the following messages in the log - alluding to a javascript setting - FYI I’m using an iPAD (and Safari)
````
&lt;!DOCTYPE html&gt;
&lt;html lang=&#34;en&#34;&gt;
  &lt;head&gt;
    &lt;meta charset=&#34;UTF-8&#34; /&gt;
    &lt;link rel=&#34;icon&#34; href=&#34;favicon.ico&#34; /&gt;
    &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1.0&#34; /&gt;
    &lt;meta name=&#34;theme-color&#34; content=&#34;#000000&#34; /&gt;
    &lt;meta name=&#34;description&#34; content=&#34;Jellyfin stats for the masses&#34; /&gt;
    &lt;link rel=&#34;apple-touch-icon&#34; href=&#34;icon-b-192.png&#34; /&gt;
    &lt;script src=&#34;env.js&#34;&gt;&lt;/script&gt;
    &lt;!--
      manifest.json provides metadata used when your web app is installed on a
      user&#39;s mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    --&gt;
    &lt;link rel=&#34;manifest&#34; href=&#34;manifest.json&#34; /&gt;
    &lt;!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.
all values are hidden
      Unlike &#34;favicon.ico&#34; or &#34;favicon.ico&#34;, &#34;%PUBLIC_URL%/favicon.ico&#34; will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    --&gt;
    &lt;title&gt;JellyStat&lt;/title&gt;
    &lt;script type=&#34;module&#34; crossorigin src=&#34;./assets/index-864c1f9d.js&#34;&gt;&lt;/script&gt;
    &lt;link rel=&#34;modulepreload&#34; crossorigin href=&#34;./assets/vendor-2d4d1dd6.js&#34;&gt;
    &lt;link rel=&#34;stylesheet&#34; href=&#34;./assets/index-ac22111c.css&#34;&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;noscript&gt;You need to enable JavaScript to run this app.&lt;/noscript&gt;
    &lt;div id=&#34;root&#34;&gt;&lt;/div&gt;
    
  &lt;/body&gt;
&lt;/html&gt;
````

**Comment by nodecentral** [comment]
Just to be sure you have all the information you need from my logs, he’s what’s occurred since my last failed saves ..
````

    { TraceIndex: 6, line: 'node:_http_client:103:11' },
    { TraceIndex: 7, line: 'node:_http_client:506:5' },
    { TraceIndex: 8, line: 'node:events:520:28' },
    { TraceIndex: 9, line: 'node:internal/streams/destroy:170:8' },
    { TraceIndex: 10, line: 'node:internal/streams/destroy:129:3' },
    {
      TraceIndex: 11,
      line: '/app/node_modules/axios/dist/node/axios.cjs:4224:41'
    },
    { TraceIndex: 12, line: 'node:internal/process/task_queues:105:5' },
    {
      TraceIndex: 13,
      line: '/app/backend/classes/jellyfin-api.js:486:24'
    },
    {
      TraceIndex: 14,
      line: 'at async /app/backend/routes/api.js:279:24'
    }
  ],
  Message: 'connect ETIMEDOUT 192.168.102.134:8096',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:841:14',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/node_modules/axios/dist/node/axios.cjs:841:14'
    },
    {
      TraceIndex: 2,
      line: '/app/node_modules/axios/dist/node/axios.cjs:3106:25'
    },
    { TraceIndex: 3, line: 'node:events:520:28' },
    {
      TraceIndex: 4,
      line: '/app/node_modules/follow-redirects/index.js:38:24'
    },
    { TraceIndex: 5, line: 'node:events:520:28' },
    { TraceIndex: 6, line: 'node:_http_client:103:11' },
    { TraceIndex: 7, line: 'node:_http_client:506:5' },
    { TraceIndex: 8, line: 'node:events:520:28' },
    { TraceIndex: 9, line: 'node:internal/streams/destroy:170:8' },
    { TraceIndex: 10, line: 'node:internal/streams/destroy:129:3' },
    {
      TraceIndex: 11,
      line: '/app/node_modules/axios/dist/node/axios.cjs:4224:41'
    },
    { TraceIndex: 12, line: 'node:internal/process/task_queues:105:5' },
    {
      TraceIndex: 13,
      line: '/app/backend/classes/jellyfin-api.js:486:24'
    },
    {
      TraceIndex: 14,
      line: 'at async /app/backend/routes/api.js:279:24'
    }
  ],
  Message: 'connect ETIMEDOUT 192.168.102.134:8096',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:841:14',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/node_modules/axios/dist/node/axios.cjs:841:14'
    },
    {
      TraceIndex: 2,
      line: '/app/node_modules/axios/dist/node/axios.cjs:3106:25'
    },
    { TraceIndex: 3, line: 'node:events:520:28' },
    {
      TraceIndex: 4,
      line: '/app/node_modules/follow-redirects/index.js:38:24'
    },
    { TraceIndex: 5, line: 'node:events:520:28' },
    { TraceIndex: 6, line: 'node:_http_client:103:11' },
    { TraceIndex: 7, line: 'node:_http_client:506:5' },
    { TraceIndex: 8, line: 'node:events:520:28' },
    { TraceIndex: 9, line: 'node:internal/streams/destroy:170:8' },
    { TraceIndex: 10, line: 'node:internal/streams/destroy:129:3' },
    {
      TraceIndex: 11,
      line: '/app/node_modules/axios/dist/node/axios.cjs:4224:41'
    },
    { TraceIndex: 12, line: 'node:internal/process/task_queues:105:5' },
    {
      TraceIndex: 13,
      line: '/app/backend/classes/jellyfin-api.js:486:24'
    },
    {
      TraceIndex: 14,
      line: 'at async /app/backend/routes/api.js:279:24'
    }
  ],
  Message: 'connect ETIMEDOUT 192.168.102.134:8096',
  url: undefined
  }
````

**Comment by CyferShepard** [comment]
Hey @nodecentral , just to confirm, this section, 
`&lt;!DOCTYPE html&gt;
&lt;html lang=&#34;en&#34;&gt;
  &lt;head&gt;
    &lt;meta charset=&#34;UTF-8&#34; /&gt;
    &lt;link rel=&#34;icon&#34; href=&#34;favicon.ico&#34; /&gt;
    &lt;meta name=&#34;viewport&#34; content=&#34;width=device-width, initial-scale=1.0&#34; /&gt;
    &lt;meta name=&#34;theme-color&#34; content=&#34;#000000&#34; /&gt;
    &lt;meta name=&#34;description&#34; content=&#34;Jellyfin stats for the masses&#34; /&gt;
    &lt;link rel=&#34;apple-touch-icon&#34; href=&#34;icon-b-192.png&#34; /&gt;
    &lt;script src=&#34;env.js&#34;&gt;&lt;/script&gt;
    &lt;!--
      manifest.json provides metadata used when your web app is installed on a
      user&#39;s mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    --&gt;
    &lt;link rel=&#34;manifest&#34; href=&#34;manifest.json&#34; /&gt;
    &lt;!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.
all values are hidden
      Unlike &#34;favicon.ico&#34; or &#34;favicon.ico&#34;, &#34;%PUBLIC_URL%/favicon.ico&#34; will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    --&gt;
    &lt;title&gt;JellyStat&lt;/title&gt;
    &lt;script type=&#34;module&#34; crossorigin src=&#34;./assets/index-864c1f9d.js&#34;&gt;&lt;/script&gt;
    &lt;link rel=&#34;modulepreload&#34; crossorigin href=&#34;./assets/vendor-2d4d1dd6.js&#34;&gt;
    &lt;link rel=&#34;stylesheet&#34; href=&#34;./assets/index-ac22111c.css&#34;&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;noscript&gt;You need to enable JavaScript to run this app.&lt;/noscript&gt;
    &lt;div id=&#34;root&#34;&gt;&lt;/div&gt;
    
  &lt;/body&gt;
&lt;/html&gt;`

Does that appear in the docker logs or console logs?

**Comment by nodecentral** [comment]
Hi @CyferShepard - it's from the Docker logs.

**Comment by CyferShepard** [comment]
okay thanks, im not really sure how to replicate this so it may take me a while. can you try this but, change the api and url, then on another device, or even in incognito mode, go to the settings page and see if its still the old value or the new value

**Comment by nodecentral** [comment]
Sadly the same thing via Chrome and ingconito mode on the iPad

**Comment by nodecentral** [comment]
Hi @CyferShepard  - is there anything else I can do to make this work, sadly I can’t use Jellystat until I can update the details.  Is it perhaps in a config file I could manually access and change?

**Comment by CyferShepard** [comment]
Hey @nodecentral , sorry i didnt actually debug this in depth, i initially got stuck on trying to replicate the error. not really sure whats causing it or how to replicate it in my test instance. theres no config for this. the only way is to manually set the values in the postgres db

**Comment by nodecentral** [comment]
Thanks so much for responding @CyferShepard, if it's not something you can reproduce then I completely appreciate it's not something you'd want to spend time on.. 

To try one final things - as I never considered or even know where to state to edit a value in the postgres db before, do you know if that is that possible? I'll try anything to help get this to work :-)

**Comment by CyferShepard** [comment]
so i added 2 new environmental variables to allow you to override these values. it doesnt store it to the db, just replaces the db value when its being used. the new envs are called JF_HOST and JF_API_KEY. Just a heads up however. i dont have any validation on this field. and depending on the values you enter, if not formatted correctly. it could cause bugs or errors in the logs. an example of something that should work is 
`JF_HOST : http://192.168.0.1:8096`
`JF_API_KEY: xxxxxxxxxxxxxxxxx`

**Comment by nodecentral** [comment]
Many Thanks @CyferShepard 

I’ll give it a go with the latest image you have ..

````
version: '3'

services:
  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /share/Container/jellystat/postgres-data:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "my-secret-jwt-key"
      JF_HOST: http://192.168.1.234:8096
      JF_API_KY: moienfoeifnoweifnwoeinfwoeifnwoeinf
      TZ: Europe/London
    volumes:
      - /share/Container/jellystat/jellystat-backup-data:/app/backend/backup-data
    ports:
      - "8097:3000"
    depends_on:
      - jellystat-db
      
networks:
  default:

volumes:
  postgres-data:
  jellystat-backup-data:

logging:
  driver: "json-file"
  options:
    max-file: "5" # number of files or file count
    max-size: "10m" # file size
```a

**Comment by CyferShepard** [comment]
Hey @nodecentral , its not on `latest`, it would be on `unstable`. Only new releases have the `latest` tag

**Comment by nodecentral** [comment]
Hi @CyferShepard 

Sadly, no luck with the unstable version, even as environment variables they are not showing up. Ok, to try again from the start removed all web cache, delete all Postgres dbs - and even after that I can't get past it the initial 'validating' step?

![image](https://github.com/user-attachments/assets/d2ed12b5-2917-46ae-87a7-83eb36a83cce)

The logs only show this..

![image](https://github.com/user-attachments/assets/a5bbc61e-13c3-40b6-b809-ab9d2682d1df)

It won't progress any further..

Any ideas are there more verbose logs I can check ?

**Comment by CyferShepard** [comment]
can you check he browsers console log? its located in your browsers dev tools

**Comment by nodecentral** [comment]
Sure, here you go, reminder my primary device is an iPad

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/15d97aa2-6126-4422-ab47-ffacd4a2da35">

I checked my Safaris settings and javascript is (and always has been) enabled.

<img width="915" alt="image" src="https://github.com/user-attachments/assets/9801f6db-f3ef-4f41-b442-ef3ffaac5f27">

Other entries of interest are as follows

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/d521749c-245c-4d94-96d7-29bb0c7d3212">


It’s important to note, that both Jellyfin and jellystat are running on the same host 192.168.102.134, Jellyfin is port :8096 and jellystat is port :8097

**Comment by CyferShepard** [comment]
can you try `host.docker.internal` instead of localhost, so it would be `http://host.docker.internal:8096`

**Comment by nodecentral** [comment]
Same 400 error with http://host.docker.internal:8096/ as it was with http://127.0.0.1:8096/.  If i try the actual Jellyfin IP, on http://192.168.102.134:8096/ it shows validating, but that’s it, nothing more it stays there.

**Comment by CyferShepard** [comment]
hey @nodecentral , is this still an issue?
