### ISSUE TITLE
Last x Days on Home Page

### ISSUE THREAD

**Issue by ShakeSp33r** [CyferShepard/Jellystat#253]
If you open the home page the system defaults to Last 30 Days, however, I would just like to see the last 7 days, so I change it to 7 and next time I open the page again I have to change it again. 

If the Last X Days field is change, could this not be saved in either the postgress DB of even a config file and loaded back up with the page to only show that info. This value can then also be later used to filter through the entire site, to show last X days activity, statistics, recently added etc.

The value could also be pulled from the settings screen.

**Additional context**
![Screenshot 2024-10-03 at 08 54 39](https://github.com/user-attachments/assets/bc4ad744-ad78-4b53-aec4-80fd89d9ee4d)

**Comment by CyferShepard** [comment]
Note to self, review where possible to store values in local storage for per device preferences.

**Comment by CyferShepard** [comment]
Feature has been pushed to `unstable`
