### ISSUE TITLE
 Cannot change password when old password doesn't meet requirements

### ISSUE THREAD

**Issue by Preclowski** [CyferShepard/Jellystat#254]
**Describe the bug**
Cannot change password when old password doesn't meet requirements.

I set initial password to "admin", not I cant change it because "Password Must be at least 6 characters long".

Password requirements should not apply to "Old password".

**Environment Details (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome, Mozilla]
 - Jellystat Version [e.g. 1.0.0] 1.1.0
 - Jellyfin Version [e.g. 10.0.5]

**To Reproduce**
1. Create user with password "12345"
2. Log in
3. Try to change password to "12345678"
4. See error "Password Must be at least 6 characters long"

**Expected behavior**
I want to be able to change any "old password" to compliant one

**Comment by alternativesurfer** [comment]
Issue still exists on a new install

![Image](https://github.com/user-attachments/assets/91ec4d13-1f69-411e-a7c5-a8798ea93647)

**Comment by ItsKiddow** [comment]
@alternativesurfer 

That's correct. @CyferShepard will need to merge my commit into the release. As of right now it's only in "Unstable" branch.
Surely, they have a lot on their plate and thus weren't able to include the change yet. :)
