### ISSUE TITLE
Not tracked Libraries show in Statistics

### ISSUE THREAD

**Issue by alexanderkuenzel** [CyferShepard/Jellystat#258]
**Describe the bug**
When I disable tracking for a specific library it is hidden in "Librares" Tab, but still shown as graph in Statistics.

**Environment Details (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Jellystat Version: 1.1.0
 - Jellyfin Version: 10.9.11

**To Reproduce**
1. Go to Settings
2. Go to Library Settings
3. Uncheck "Tracked" on a library
4. Reload page
5. Library is hidden on Librarys Tab (can be shown by clicking the eye in the top-right corner
6. Library shows still on graphs in Statistics Tab.

**Expected behavior**
Library should be also hidden on Statistics Tab.

**Screenshots**
<img width="1442" alt="Bildschirmfoto 2024-10-20 um 10 45 43" src="https://github.com/user-attachments/assets/4af19efb-0fac-43d8-ad77-91eaa262bb16">
Libarary "Videos" has "Tracked" unchecked.
<img width="1676" alt="Bildschirmfoto 2024-10-20 um 10 47 55" src="https://github.com/user-attachments/assets/4d9bccc4-43d6-4af3-a35b-bc3593237eea">
Library "Videos" is still be shown in Graph in Statistics Tab.

**Task Logs**
If applicable, add Task Logs for your problem.

**Container Logs**
If applicable, add Container Logs for your problem.

**Additional context**

**Comment by CyferShepard** [comment]
Hey @alexanderkuenzel , is this still an issue?

**Comment by alexanderkuenzel** [comment]
Hey @CyferShepard, this is working now. Thank you!
