### ISSUE TITLE
Feature Request: Ability to delete media from Jellystat

### ISSUE THREAD

**Issue by CyferShepard** [CyferShepard/Jellystat#266]

**Comment by F1DNA** [comment]
Why would this be necessary?  So many ways to manage your media files, your observability stack doesn't need to do this.

**Comment by F1DNA** [comment]
@CyferShepard Fair enough.  Just wanted to throw my 2 cents in.  Obv if this is added I don't have to give Jellystat write access to my media collection and/or use the feature and I won't.  I just feel the "Too many hands in the cookie jar" philosophy can be used here.  Hell, I didn't even give Jellyfin write access to my media until I wanted some of the extra features like theme songs and such.  And even then I did so begrudgingly .  I really prefer that only my ARR stack has write access.
