### ISSUE TITLE
Limit playback count to 25%

### ISSUE THREAD

**Issue by Hello-World-Traveler** [CyferShepard/Jellystat#270]
**Is your feature request related to a problem? Please describe.**

If a show is played for a few seconds then exited, it is counted as playback therefore gets added to Playback Total, this will make some users very high when they are testing playback and so on.

**Describe the solution you'd like**

Setting to change how long media has to be played to be counted.

**Describe alternatives you've considered**

None

**Additional context**
Minimum 10 minutes if not at 25%

**Comment by zodac** [comment]
Chiming in that this is also something that I'd like to see filtered out. I think there was a previous fix to filter out playback with only 0s, this should probably be done in a similar place?
https://github.com/CyferShepard/Jellystat/commit/a07daf84f07e87ba6265060d1de719a823697b0c

Whatever the fix (absolute playtime vs percentage playtime), I think configuring the value (ideally through an environment variable) would be valuable.

It's been on my mind recently, if I get the opportunity I'll take a look at sending in a PR.

**Comment by Hello-World-Traveler** [comment]
What duration are you thinking of using? is it possible to count a full JF playback?

**Comment by zodac** [comment]
I've added an environment variable you can set with a minimum number of seconds for a playback to count. For me, I'm mostly concerned with autoplaying media and getting 1-2 playback, so 10s is enough for me. But a static 600s might work for you?

I wasn't sure if the playback object had a 'percentagePlayed' variable which could be used instead. But maybe comment on that PR, and let CyberShepard know what you think?

**Comment by zodac** [comment]
I did put in the documentation that the variable is in seconds, I think most people interested in this level of filtering could probably figure out what value they need.

I was tempted to allow for values with time units, like '10s', '15m', '2h'. But it's more complicated than it needs to be, and might even add more confusion. So I think keeping it simple for now is best.

**Comment by Hello-World-Traveler** [comment]
Sorry I should had been more clear, I was talking about the read me (information).

**Comment by zodac** [comment]
Oh, I think what I've put should be sufficient? I clearly states it is in seconds, it shouldn't be a huge step for users to convert minutes/hours to seconds, and I'd rather not clutter the description with some arbitrary examples.

That being said, the PR hasn't been reviewed by CyberShepard yet, so if he thinks the same, or you wish to comment in the PR, in can make the change then. 👍

**Comment by Hello-World-Traveler** [comment]
Good point. Thanks for the PR!
