### ISSUE TITLE
Creating a Backup Crashes NodeJS

### ISSUE THREAD

**Issue by CornHead764** [CyferShepard/Jellystat#29]
When initiating a backup of Jellystat, nodeJS crashes because it is not able to open the backup file/directory with the below error:

![image](https://github.com/CyferShepard/Jellystat/assets/19508732/2903c024-a5db-4d9f-ae50-ac314383b0b6)

Looking at backend/backup.js, the issue appears to be with the backupPath variable on line 42, as it contains a dot a the beginning of the line:

const backupPath = `./backup-data/backup_${now.format('yyyy-MM-DD HH-mm-ss')}.json`;

**Comment by CyferShepard** [comment]
This seems like an issue with the docker volume. the . is needed to tell it to look into the current directory and then go one folder in called backup. But if the volume is not mounted correctly or cannot be accessed it throws this error. il add some checks to prevent this from crashing the entire backend

**Comment by CyferShepard** [comment]
Hi @CornHead764 , a fix has been pushed with version 1.0.3. This is to prevent crashing the entire backend and also adding a failure reason to the logs.

**Comment by CornHead764** [comment]
> This seems like an issue with the docker volume. the . is needed to tell it to look into the current directory and then go one folder in called backup. But if the volume is not mounted correctly or cannot be accessed it throws this error. il add some checks to prevent this from crashing the entire backend

From looking at the example compose yaml file on docker hub, I think I see the confusion. The volume maps /app/backend/backup-data on the host side to /backup-data on the container side. These probably just need to get switched around then.
