### ISSUE TITLE
Bug/Feature Request: Activity Date/Time Format

### ISSUE THREAD

**Issue by CornHead764** [CyferShepard/Jellystat#32]
It looks like if you have the hour format to 12 hour, Noon/Midnight is 00 rather than 12, at least for the start time listed on the activity page.

![image](https://github.com/CyferShepard/Jellystat/assets/19508732/ec5e3ad7-81e2-4581-82f3-464d7481e3db)

On a related note, would it be possible to add a setting for customizing the date/time format? Us Americans like our MM/DD/YYYY format :)

**Comment by CyferShepard** [comment]
Hi @CornHead764 , il work on something to achieve this, may only come in the next update as im trying to squash some bugs first. Will also look into the noon/midnight issue
