### ISSUE TITLE
When user with long username streams  stream session info becomes unreadable

### ISSUE THREAD

**Issue by Hydranet** [CyferShepard/Jellystat#36]
When user with long username streams  stream session info becomes unreadable. It seems to only be with tv series episodes since they have longer names and take in more space. I'll attach some screenshot so you can see the comparison.
![Screenshot from 2023-05-30 18-27-35](https://github.com/CyferShepard/Jellystat/assets/22844936/2d642cad-6655-4b90-9fec-80d7e5c67969)
![Screenshot from 2023-05-30 18-29-01](https://github.com/CyferShepard/Jellystat/assets/22844936/bf26fb27-ab6c-4c51-a15f-8a72c9550773)
![Screenshot from 2023-05-30 18-30-01](https://github.com/CyferShepard/Jellystat/assets/22844936/52f0ee9a-1136-4da5-a638-f19f94cfaed6)

**Comment by CyferShepard** [comment]
This seems more like an issue with episode name length, il do some testing and ellipse the overflowing data with a tooltip hover action so that it doesnt get squashed but the data is still visible when needed

**Comment by Hydranet** [comment]
You can close this, I changed all my usernames to normal username instead of using email addresses as username but it still could be an issue if someone decides to use long usernames.
