### ISSUE TITLE
Libraries Empty: Cannot read properties of undefined

### ISSUE THREAD

**Issue by SinisterCrayon** [CyferShepard/Jellystat#37]
Just connected Jellystat to my Jellyfin server and I'm getting the error "Error: TypeError: Cannot read properties of undefined" when updating libraries so the libraries turn up as blank. I am seeing Current Sessions as well as "Recently Added" in the homescreen but nothing else.

Logs from the update;

Syncing... 1/3
Beginning Library Item Sync
Error: TypeError: Cannot read properties of undefined (reading 'e0e450d79686e5b934f248ec2a8ac620')
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 0 Rows Updated.
0 Seasons Removed.
Episodes: 0 Rows Inserted. 0 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
0 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete

No significant logs on the console... this is deployed in Docker.

**Comment by CyferShepard** [comment]
Hi @SinisterCrayon , can you get the latest version, re-run the sync and send me the new log? the new version isnt a fix, its just performs more detailed logging so we can better debug issues

**Comment by SinisterCrayon** [comment]
Done. Now running version 1.0.4.3. The log was the same except for the specific error line which now looks like this;

Beginning Library Item Sync
at jf_library_items_mapping (/app/backend/models/jf_library_items.js:45:98: Error: TypeError: Cannot read properties of undefined (reading 'e0e450d79686e5b934f248ec2a8ac620')

Console logs show nothing out of the ordinary from what I can see.

**Comment by CyferShepard** [comment]
I see the issue now, my validation was referencing the wrong field. Gonna check the API docs one more time and hopefully next update will be the one to solve it

**Comment by SinisterCrayon** [comment]
Excellent!!! Thank you. I'll stay tuned for a code update and then report back when it's tested :)

**Comment by CyferShepard** [comment]
Try one more pull, i didnt bump the version number on this one as it was such a small change

**Comment by SinisterCrayon** [comment]
I think that might have done it. It's definitely doing something though I can't tell what because the dashboard blanks almost immediately. It's a large library so I'll let it run and report back when it finishes. Definitely looks better than before though (both the node and postgres processes are showing CPU utilization)

**Comment by CyferShepard** [comment]
Fingers crossed, i do so another potential issue on the frontend side of things but hopefully the sync part of things work

**Comment by CyferShepard** [comment]
Sure, create a new ticket, and include a screenshot of your browser console. Il leave this issue open just incase and close it once all is resolved

**Comment by CyferShepard** [comment]
Closing since all related issues are resolved
