### ISSUE TITLE
Frontend Blank after Library Update

### ISSUE THREAD

**Issue by SinisterCrayon** [CyferShepard/Jellystat#40]
Frontend is blank browsing to port 3000. Page begins to populate but then everything on the frontend disappears and is blank. Can't get to any logs that I can see to upload to diagnose the issue.

Tried clearing cache and cookies. Tried a different browser (Firefox and Chrome in that order). Result is the same.

**Comment by CyferShepard** [comment]
Hi @SinisterCrayon , can you include a screenshot of your browser console when on that page?

**Comment by SinisterCrayon** [comment]
![Screenshot from 2023-05-31 08-12-16](https://github.com/CyferShepard/Jellystat/assets/57157713/a1d13fb0-a17b-4af1-8be8-31aa3d66587c)
![Screenshot from 2023-05-31 08-12-19](https://github.com/CyferShepard/Jellystat/assets/57157713/89ef84a2-b46f-41de-b4ea-86ace3530942)

**Comment by CyferShepard** [comment]
I pushed a quick fix, let me know if that solves it

**Comment by CyferShepard** [comment]
Its cool, had a feeling this may happen but glad its all sorted
