### ISSUE TITLE
Media Libraries of type Other are not loaded

### ISSUE THREAD

**Issue by vincentscode** [CyferShepard/Jellystat#41]
Jellystat only shows one of the available media libraries. The logs don't show anything immediately related to this. I have tried to resync multiple times and am running Version `1.0.4.5`.

![image](https://github.com/CyferShepard/Jellystat/assets/26576880/0121985d-a45d-4648-bf57-33daea467bbe)
![image](https://github.com/CyferShepard/Jellystat/assets/26576880/b348291a-79df-4623-b49e-a0a0bc1f06c7)

Some items from the not showing libraries are shown under `Recently added` but clicking on them results in a `404`.

This might be related to #34?

**Comment by CyferShepard** [comment]
Hi @vincentscode , this is a separate issue, I had the sync only accept certain library types. Specifically Music, Movies, TV Shows, i see your library types are of type Other. I did this to avoid syncing Collections. Il change this in the next update probably by tomorrow.

**Comment by vincentscode** [comment]
I see, thanks! I suppose I should switch over to using `Mixed Movies and Shows` as my library type now that it is available.

**Comment by CyferShepard** [comment]
Oh i didnt know that was a new option, il add that in aswell
