### ISSUE TITLE
Vulnerability: Silent fallback to default JWT Key 

### ISSUE THREAD

**Issue by vincentscode** [CyferShepard/Jellystat#44]
https://github.com/CyferShepard/Jellystat/blob/d9d5cad5d42a1165bd8e8318f13d541892a1ea79/backend/auth.js#L6

The API should not silently fall back to a hardcoded JWT token. This may lead to vulnerable instances.

**Comment by CyferShepard** [comment]
Change has been made to throw an error instead of silently falling back to a default value
