### ISSUE TITLE
When movie title is too long the text comes out of the box

### ISSUE THREAD

**Issue by LuckyS7evin** [CyferShepard/Jellystat#51]
Hi,
First, thank you for this great project, I was waiting for a long time for a more practical tool than the Jellyfin Reporting plugin.
I have an issue with movies that have a long title, the text comes out of the box. See screenshot below :

![image](https://github.com/CyferShepard/Jellystat/assets/117847731/6826e666-49d6-4780-afc8-b57ce3a369f3)

**Comment by CyferShepard** [comment]
Hi, Thanks so much @LuckyS7evin , This been fixed and will ship in the next update
