### ISSUE TITLE
After renaming users in Jellyfin Jellystat shows old usernames under User tab

### ISSUE THREAD

**Issue by Hydranet** [CyferShepard/Jellystat#57]
After having renamed my users in Jellyfin under the user tab the old usernames still  there and aren't replaced with the new usernames, however when a user streams something the streamed session does show up under sessions with their new username. When you go to the "Users" tab, then click on the old username, to then click on "Activity"  you then see all the previous streams under their new username. So it seems like the only place the new username doesn't show up is under the "User" tab.

**Comment by CyferShepard** [comment]
Hi @Hydranet , this has been resolved on the unstable branch and will be added to main once other aspects are completed
