### ISSUE TITLE
Feature request: Select jellyfin admin user

### ISSUE THREAD

**Issue by dertasiu** [CyferShepard/Jellystat#58]
Hello!

I have different admin users, but only one of them has access to everything. The problem is that the "main" admin user (the first one) doesn't have access to every library.
In the sync.js code, there is a line where it selects the first admin of the collection returned.
https://github.com/CyferShepard/Jellystat/blob/main/backend/sync.js#L487
```
const admins = await _sync.getAdminUser(refLog);
const userid = admins[0].Id;
```

If we could select the jellyfin's admin account where Jellystat should pull the libraries from, it would be nice.

**Comment by CyferShepard** [comment]
Hi @dertasiu , il work on adding in a selector so you are able to select a preferred admin user

**Comment by CyferShepard** [comment]
Hi, this has been added under the settings tab

**Comment by IkkeElias1** [comment]
what if theres multiple admins?
