### ISSUE TITLE
Empty Library

### ISSUE THREAD

**Issue by kesm** [CyferShepard/Jellystat#59]
Hello I'm using Jellyfin 10.9 (nigthly) and I got everything working except the library page

![image](https://github.com/CyferShepard/Jellystat/assets/6907912/8b779d35-310c-4acc-a738-1d4afc7be7a8)

It looks like the same issue than https://github.com/CyferShepard/Jellystat/issues/28 but not the same error message.

FYI the home page is also working on my side (currently watching and recently added)

I'm using the docker compose on unraid to run Jellystat

**Comment by CyferShepard** [comment]
Hi @kesm , can you check the sync logs under settings for any errors? also can you confirm if your admin users have access to these libraries?

**Comment by kesm** [comment]
Here is the log, it seems there is no errors
```Syncing... 1/3
Beginning Library Item Sync
0 Library Items Removed.
Item Sync Complete
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 0 Rows Updated.
0 Seasons Removed.
Episodes: 0 Rows Inserted. 0 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
0 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete```

and yes my admin user have access to all libraries

**Comment by CyferShepard** [comment]
This looks like a similar sync issue another user is experiencing (current discussion on our discord) , im still looking into it and may have an update on the nightly in the next day or two. Will post here once its out

**Comment by CyferShepard** [comment]
Hi @kesm , can you pull the latest version from unstable and test it out, if the logs still say 0 try to select a preferred admin under settings and then rerun the sync

**Comment by kesm** [comment]
It's ok now with the instable version, thanks a lot!
