### ISSUE TITLE
Bug: New Backup gets deleted

### ISSUE THREAD

**Issue by mLgz0rn** [CyferShepard/Jellystat#61]
Hello!

I just noticed that when Jellystat creates a new backup, that new backup is detected as an old backup and gets deleted.
None of the other "old" backup are getting deleted.

```
Starting Backup
Begin Backup /app/backend/backup-data/backup_2023-07-15 17-57-45.json
Saving 4 rows for table jf_libraries
Saving 536 rows for table jf_library_items
Saving 153 rows for table jf_library_seasons
Saving 1476 rows for table jf_library_episodes
Saving 17 rows for table jf_users
Saving 620 rows for table jf_playback_activity
Saving 620 rows for table jf_playback_reporting_plugin_data
Saving 1742 rows for table jf_item_info
Backup Complete
Removing old backups
/app/backend/backup-data/backup_2023-07-15 17-57-45.json has been deleted.
1 backups removed.
```

Also, on the backup page, date created just shows "01/01/1970, 01:00:00" for all backup.

Im running Jellystat 1.0.5.0.

Kind regards!

**Comment by CyferShepard** [comment]
Hi @mLgz0rn , would you mind showing me your portainer logs just after running a backup? This is really strange behaviour, it could be a weird permissions issue with your docker container aswell but the portainer logs will help us clear that up

**Comment by mLgz0rn** [comment]
I deleted the backup that were already there, and after that it started working.

Date created still shows the same though.

**Comment by CyferShepard** [comment]
Oh cool, Il have to check what's going on with the dates but I'm glad you atleast have a backup
