### ISSUE TITLE
Available on UnRaid

### ISSUE THREAD

**Issue by glbjr29** [CyferShepard/Jellystat#63]
Hello,
Will this ever be released out on UnRaid?

**Comment by CyferShepard** [comment]
Hi @glbjr29 , I'm not sure. I'd like to target as many platforms as possible, so Il look into supporting that platform aswell

**Comment by Upmacc** [comment]
Hi @glbjr29 and @CyferShepard, fyi I have just submitted an app template to the UnRaid community app devs.  
Will update once its approved.

**Comment by Upmacc** [comment]
Hey @glbjr29, fyi Jellystat is now available in Unraid community apps.  Let me know if you have any issues.

**Comment by CyferShepard** [comment]
Hey @Upmacc , thanks for getting this pushed through, I hadn't had the time to look into this so this would have take a lot longer to get done.

**Comment by glbjr29** [comment]
> Hey @glbjr29, fyi Jellystat is now available in Unraid community apps. Let me know if you have any issues/questions.

Have you tried setting it up? I keep get the Error: Unable to connect to Jellystat Backend when trying to open the GUI.

**Comment by Upmacc** [comment]
Hi @glbjr29, yep I have it running.
You need to ensure the Postgres database container is already running before starting the Jellystat container.

**Comment by hiddenretro** [comment]
@Upmacc I have tried this and I still cant get past the "Unable to connect to jellystat backend". Is there something we need to change in the JWT_SECRET portion?

**Comment by Upmacc** [comment]
Hello @hiddenretro,
You should be able to set the JWT to anything you would like.
Ensure the Postgres port and IP is updated in the template with that of your Postgres instance.

Are you getting any other errors in your Jellystat log?  Upon a container restart can it find the database?

If your still having issues, I can possibly help via discord.

**Comment by hiddenretro** [comment]
@Upmacc  thanks for the quick reply. I actually just got it working. I had to reinstall my postgres docker. Since I am only using postgres for jellystat is was no biggie. I appreciate the help!

**Comment by Upmacc** [comment]
Sweet, great to hear @hiddenretro.
At this stage if the Jellystat DB doesn't create properly, then you do have to delete the db so Jellystat recreates it.
Jellystat requires the default Postgres user to be able to create the DB too.

Out of curiosity which version of Postgres are you using?

**Comment by hiddenretro** [comment]
I was trying on Postgres14 and was having issues. Installed Postgres15 and it worked seamlessly.

**Comment by kizilcali81** [comment]
Hi @CyferShepard, somehow it is not available anymore in the CA of Unraid. Can you please have a look on this? It would be great, if it is available again.

**Comment by TheMapledCog** [comment]
Hi @kizilcali81, let me check in on this.
It was temporarily removed due to my profile name update.

**Comment by charlieny100** [comment]
Any idea when it will be back in unraid?

**Comment by TheMapledCog** [comment]
Hi @charlieny100
This is currently with the Community Apps team.  I have followed up with them, however they are pretty busy in general so I don't have an estimation at this stage.  
I will update here as soon as I hear back.

**Comment by Mortirreke** [comment]
@TheMapledCog It is available again, thanks!
