### ISSUE TITLE
High CPU usage when running Jellystat

### ISSUE THREAD

**Issue by harsh0596** [CyferShepard/Jellystat#66]
I'm running jellystat using docker and I'm getting high CPU usage at all times. CPU goes down to normal when i stop the container

![top](https://i.imgur.com/stpzw45.png)
![omv](https://i.imgur.com/q15a04B.png)

CPU usage after stopping the container:
![omv-after](https://i.imgur.com/c9Lq3rI.png)

OS: OpenMediaVault (debian linux)
CPU: i3-10105
Ram: 16gb
Media Library size: ![size](https://i.imgur.com/G1pw4hw.png)

**Comment by CyferShepard** [comment]
Hi @harsh0596 , do you mind also including the specs of your system. EG OS, CPU,Ram size etc. Aswell as a general size of your media library EG 100+ videos

**Comment by harsh0596** [comment]
> Hi @harsh0596 , do you mind also including the specs of your system. EG OS, CPU,Ram size etc. Aswell as a general size of your media library EG 100+ videos

added

**Comment by CyferShepard** [comment]
Thanks. Il look into this and see how I can optimise it better.

**Comment by cleming** [comment]
![image](https://github.com/CyferShepard/Jellystat/assets/9937872/4ecaad65-03ec-42ef-8d28-bdb6ab0ac197)
![image](https://github.com/CyferShepard/Jellystat/assets/9937872/394c64b9-81c3-4be1-ac2f-75b121b9ad50)
![image](https://github.com/CyferShepard/Jellystat/assets/9937872/66a592ae-e4a0-4e76-a95b-56b66376844c)

Hi !
we're seeing intensive CPU and IOPS consumption here too. Feel free to reach out to me if you need metrics or any other information.

**Comment by CyferShepard** [comment]
Hi @cleming , iv managed to identify a few regions causing these spikes and have optimized them, im still working on the code but a fix for this will be out with the next version.

**Comment by linedpaper** [comment]
Looking forward to this fix.  It keeps pounding my i7, i've had to stop the container until the resource issue is resolved, but otherwise it looks good so far!

**Comment by dinosmm** [comment]
I am seeing this too. Please correct me if I'm wrong, but my culprit is 'node server.js' process which the container is starting and it ends up taking 30-40% CPU and increases the load on my system. This happens constantly.

**Comment by CyferShepard** [comment]
Hi @dinosmm , yes this is correct, its due to how imports and activity monitor processes are being run, im currently optimizing this to reduce the cpu and memory load

**Comment by CyferShepard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved Performance](https://trello.com/c/s92111RP/3-improved-performance)

**Comment by EVOTk** [comment]
Same issue for me. Keep my cpu at about 20% ( i3-10100T )

**Comment by CyferShepard** [comment]
Hi Everyone, iv implemented some optimizations to address both high CPU and Memory usage, if anyone has the time, can you pull the latest ```unstable``` image and compare to let me know if the improvements work

**Comment by CyferShepard** [comment]
Awesome, im glad it worked. The first 2 hours where probably the Full sync running (I assume you have a really large library if took that long). The Recently Added Scan is alot less resource intensive but you should see a short spike in cpu usage every hour for a second or 2, this would be that scan. Hopefully i can further improve the efficiency but i feel now it has a more acceptable resource usage

**Comment by dinosmm** [comment]
I got unstable going, but on the old database, and it kept load and CPU high again; I assumed it was scanning but the movie etc. counts weren't changing (and were completely wrong), so I deleted all the old data and recreated the container. I'll leave it to scan now, and see how it behaves after a few hours.

**Comment by dinosmm** [comment]
Is it normal that the 'Full Jellyfin Sync' is still running? It's been 6 hours since it started. This is on a 34TB library.

**Comment by EVOTk** [comment]
What is you CPU ?

With i3-10100T ~2h for ~70To

**Comment by dinosmm** [comment]
3 vCores on a VPS.

**Comment by EVOTk** [comment]
I have no experience in this sector, but VPS are generally not very powerful. I think it can take a long time on this type of machine.

**Comment by CyferShepard** [comment]
Hmmm, so im not really sure how well this scales to such a large library, How many items do you have?,also at what stage is the sync at? you should see it on the little toast notifier on the bottom right of your screen (reload the page if it doesn't show).

**Comment by dinosmm** [comment]
900 in one library, 300 in another. Jellyfin scan takes less than an hour if done from scratch though. 

> little toast notifier 

That showed briefly at the start of the scan, but hasn't shown again for hours. It doesn't show if I refresh at all.

**Comment by CyferShepard** [comment]
and do you see any activity in your resource monitors? IE CPU/ RAM usage? im trying to see if its actually running or perhaps its so slow that updates a few and far apart. If you see little to no CPU and RAM usage maybe try restarting the container and rerunning the sync, it could be frozen

**Comment by dinosmm** [comment]
Previously (a few hours ago) I could see 'node server.js' taking up 30% CPU and load up because of it, now I see it running still but much lower CPU usage, and load is down below 1 again.
I just stopped and restarted the container; as you said, the full sync job had failed, and the library totals were showing as 10 movies and a few episodes.
I started a new full sync again, let's see how it goes.
If there are any logs anywhere that you think might be useful, please do let me know where to get them and I can post them.

**Comment by CyferShepard** [comment]
There should be logs under the settings, if thats blank it means the sync failed on start/fetch. Can you also check the container logs for any error messages

**Comment by dinosmm** [comment]
Oh yea the logs box in settings was completely blank before and it is blank again now under the 'running' full sync.
Docker logs (using 'docker logs' command) doesn't show much:

```
> jfstat@1.0.8 start
> cd backend && node server.js

[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000
Activity Interval: 1000
Running Recently Added Scheduled Sync
Running Scheduled Backup
Scheduled Backup Complete
Scheduled Recently Added Sync Complete
```

**Comment by CyferShepard** [comment]
sweet, the log bog doesn't populate until the task is complete, wasn't done on purpose, just didn't get around to fixing that minor detail

**Comment by dinosmm** [comment]
Awesome, sync done and it seems it has picked up everything, except for a library I have for live concerts, which shows all zero. I know the Roku app also doesn't support those, is Jellystat also meant to not support them? Not a big issue anyway. 

Weird that the initial auto full sync didn't work, but there could be timeout/throttling issues throwing off your scanner as I have a very rclone-heavy setup.
Thank you for this update, I'll watch out for this going to stable.

**Comment by CyferShepard** [comment]
Hmm, it depends, what type of library is the Live concert? As long its not of type Boxset or type Playlist it should get pulled

**Comment by CyferShepard** [comment]
Okay, il do some research on this and how its reflected in jellyfins API. But i wont post about it here as its of topic for this issue.
