### ISSUE TITLE
Error: Unable to connect to Jellystat Backend

### ISSUE THREAD

**Issue by CyferShepard** [CyferShepard/Jellystat#7]
have the same problem but after start db, then jellyfin stats, create user works fine. I add URL and API and getting "Error: Unable to connect to Jellystat Backend"

_Originally posted by @renetsk in https://github.com/CyferShepard/Jellystat/issues/4#issuecomment-1500813108_

**Comment by reitenth** [comment]
im trying to try my hand at some css. but whenever i try to run local i get http://localhost:3000/ 
![image](https://user-images.githubusercontent.com/94771708/230733393-1aec93e7-1c87-42c1-a888-0f79fa48b25d.png)

**Comment by CyferShepard** [comment]
oh i see, your running the project itself. 
This error is because the backend is not running. 
Il need to add this to the documentation but there's 3 available commands. 

`npm start` - starts only the frontend
`npm start-server` - starts only the backend
`npm start-app` - starts both the backend and frontend

Youl need to run `npm start-app`, the reason i have it split is sometimes il need to make changes to the server component and restart it and i didn't want to wait for the react build process as the nodeJs server started up faster

**Comment by reitenth** [comment]
getting this now, here is the log it mentions. thanks for the help.

![image](https://user-images.githubusercontent.com/94771708/230734731-f6891ee0-8558-4be0-9600-3851e39571e8.png)

0 verbose cli C:\Programs\Node\node.exe C:\Programs\Node\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Programs\Node\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:e:\Projects\Github\jellystat\Jellystat\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\justi\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\justi\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm view react description dist-tags.latest homepage version time
21 verbose argv "view" "--json" "react" "description" "dist-tags.latest" "homepage" "version" "time"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:C:\Users\justi\AppData\Local\npm-cache\_logs\2023-04-08T17_21_55_273Z-
26 verbose logfile C:\Users\justi\AppData\Local\npm-cache\_logs\2023-04-08T17_21_55_273Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 http fetch GET 200 https://registry.npmjs.org/react 217ms (cache revalidated)
34 timing command:view Completed in 296ms
35 verbose exit 0
36 timing npm Completed in 329ms
37 info ok

**Comment by CyferShepard** [comment]
can you confirm if package.json exists in that location? also maybe try running npm init

**Comment by reitenth** [comment]
made it, getting this error still. with unable to connect to backend.
![image](https://user-images.githubusercontent.com/94771708/230735830-83b4eb0c-48e9-4fcb-b8aa-86335b696338.png)

**Comment by CyferShepard** [comment]
okay this now looks like it fails to connect to your postgres db, did you configure the env variables in vs code?

**Comment by CyferShepard** [comment]
To configure env variables in vs code. start by pressings Ctrl+Shift+P
Click on Open User Preferences
![image](https://user-images.githubusercontent.com/24864904/230736191-0ea5b0d6-0d1d-4e5d-90e3-1ded86a5fd01.png)

In the settings, search for env and click on Edit in settings.json.

![image](https://user-images.githubusercontent.com/24864904/230736219-caf2d3ec-0bfc-4f76-858c-d102d42d84d9.png)

This is what my settings.json file looks like

{
    "workbench.colorTheme": "Visual Studio Dark",
    "remote.SSH.remotePlatform": {
        "10.0.0.99": "linux"
    },
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "explorer.confirmDragAndDrop": false,
    "terminal.integrated.env.windows": {
    
        "POSTGRES_USER": "postgres",
        "POSTGRES_PASSWORD": "my_password",
        "POSTGRES_IP": "ip_address_of_postgress_db",
        "POSTGRES_PORT": "5432"
    }
}

**Comment by reitenth** [comment]
im using the default postgres db from the dockerhub besides the secret. here are my settings in vscode now

![image](https://user-images.githubusercontent.com/94771708/230736798-d240d666-483a-4925-b790-43076b36d052.png)

![image](https://user-images.githubusercontent.com/94771708/230736825-8a412793-f014-4d4f-89b2-1e37cade040b.png)

**Comment by CyferShepard** [comment]
youl need to change the POSTGRES_IP to the ip your postgres container is running. hostname resolution is usually handled by docker but by running in vs code it wont know how to resolve the hostname jellystat-db

**Comment by reitenth** [comment]
changed postgres to container ip and 5432 is exposed. this is log now. 
![image](https://user-images.githubusercontent.com/94771708/230740994-64d4771e-ac37-482e-929a-08c95b1a769c.png)

**Comment by reitenth** [comment]
i did docker ps and docker inspect <container ID> to get the ip.

**Comment by CyferShepard** [comment]
It seems it can't connect to the server, the connection times out, can you just run the server only as the logs from the front end is making it abit hard to read, also double check your user credentials and the IP and port, also check if you don't have any firewall rule blocking that port

**Comment by CyferShepard** [comment]
Is the docker container on the same machine your running docker? Remember you don't need the docker container up, you need the IP address of the machine docker us running on

**Comment by reitenth** [comment]
![image](https://user-images.githubusercontent.com/94771708/230743362-667ba090-e6e3-4289-bfb3-eacbada4bd8a.png)
it says my password for postgres is wrong. it is the exact same in vscode as in compose. i even made a new database and it still says password is wrong.

**Comment by reitenth** [comment]
got it working. my username for postgres was not postgres, so i had to make a database named "jfstat" specifically. that got it working. i hope i can make some contributions css wise as that is all i know a little of.

**Comment by CyferShepard** [comment]
Glad you got it working. Id definitely love some help with that. So far iv been using normal css, and css and UI design in particular is not my strong suit, so id really like any help i can get, especially since im currently switching over to use bootstrap for a more responsive UI
