### ISSUE TITLE
Error 403 on Signup

### ISSUE THREAD

**Issue by conors06** [CyferShepard/Jellystat#74]
I had some issues with backend not connecting so I messed around with my compose but I get an error 403 on signup?
![image](https://github.com/CyferShepard/Jellystat/assets/91201753/56eb84db-b434-4135-a08f-b666f12f260d)
version: '3'
services:
  jellystat-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
    - /portainer/Files/AppData/Config/jellystat/db:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'secret-string'
      restart: unless-stopped
    ports:
      - 3008:3000 #Server Port
      - 3009:3009 #websocket port
    volumes:
      - /portainer/Files/AppData/Config/jellystat/backup:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:

**Comment by CyferShepard** [comment]
Hi @conors06 , that does seem abit weird. ill have to look over the code but my best guess at the moment is you've got a partially corrupted config record in such that it thinks its configured so it wont let you sign up but because there's not credentials to take you to the login page it still shows the sign up page. maybe try deleting the db image (including the postgres data on disk) and trying again.

**Comment by CyferShepard** [comment]
so just double checked and this seems like the issue. il rework the code to prevent a similar scenario but it basically boils down to you attempted to do the setup but for some reason or another it didnt save your credentials resulting in this state of sign up page but 403 error.

**Comment by conors06** [comment]
Ye I'll try redo the setup again, its not due to me changing the 3003 port is it because I had something else running there?

**Comment by conors06** [comment]
Got it working man, had to call my database jfstat and boom

**Comment by CyferShepard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error 403 on Signup](https://trello.com/c/4jwI449N/11-error-403-on-signup)
