### ISSUE TITLE
Emby support

### ISSUE THREAD

**Issue by binarygeek119** [CyferShepard/Jellystat#82]
i would love for this to support emby. 
as jellyfin was a fork of emby it shoundnt be too hard.
i know there embystat but development seems to be stalled, plus the look of this app is better.
i would fit right in with jellyseerr.

emby api
https://github.com/MediaBrowser/Emby/wiki

**Comment by CyferShepard** [comment]
Hi @binarygeek119 , im definitely moving in this direction to try and support emby. It may take a while but it should be coming in the future. Also will be closing this issue as its  a derivative of #53
