### ISSUE TITLE
Add SQLite as an alternative

### ISSUE THREAD

**Issue by skorokithakis** [CyferShepard/Jellystat#85]
SQLite is a much easier alternative to set up/maintain to Postgres, and for low-traffic setups it's just as good. Is it possible to use it with Jellystat?

**Comment by CyferShepard** [comment]
Hi @skorokithakis , sorry it took so long to look at this issue, iv been busy with other tasks. The reason for going with postgres was that it offered enhanced stored procedure functionality. I initially looked at SQLite when i first started working on jellystat but it was not a viable solution as some complicated stored procedures or user defined functions where needed to process stats in an efficient manner which is not available in SQLite.

**Comment by skorokithakis** [comment]
Ahh that makes sense, thanks! Unfortunate, as that would really help deployments, but understandable.
