### ISSUE TITLE
Bootstrap implementation

### ISSUE THREAD

**Issue by CyferShepard** [CyferShepard/Jellystat#9]
Rework the Pages to use bootstrap so that UI becomes responsive across all displays

**Comment by reitenth** [comment]
i would like to help with this and have been learning bootstrap, but i am new to coding in general. i need help in getting it up and running. does all bootstrap have to go into the index,html? i dont know how to separate pages then. if you want, i am available on discord at reitenth#0171. thanks!

**Comment by CyferShepard** [comment]
Hi @reitenth , I'd greatly appreciate any help. You don't need to be so concerned about it but, I'm also new to certain elements of react and bootstrap so this is also a learning experience for me. No, everything doesn't need to be in the main page. Each page will have its own elements and they are what you style using the standard bootstrap classes. I'm available to chat on discord in an hour as I'm currently in the middle of a blackout.

To help get started, I suggest pulling the bootstrap branch as iv already done partial implementation.
One pulled, just run `npm install` to get the packages and `npm run start-all` to start the program

**Comment by CyferShepard** [comment]
Hi @reitenth , your discord seems to be set to block requests

**Comment by reitenth** [comment]
fixed discord. looking through the bootstrap branch right now. also, it does not appear to be a tag on the docker hub? unless its the unstable.
