### ISSUE TITLE
Versionning

### ISSUE THREAD

**Issue by LaSylv** [CyferShepard/Jellystat#90]
Is there any plan on doing some docker image versionning ?

I can work on that if it's on the roadmap, if you have a workflow you want to be implemented

**Comment by CyferShepard** [comment]
Hi @LaSylv , yes there is a plan for it. as mentioned in #73. There's no workflow in place as iv been doing this solo and winging it. you can work on it if you want and any assistance would be appreciated. Right now I'm just using basic semver practices which i plan to start tagging docker images with going forward, however if you find a better way of doing them id be open to suggestions.
