### ISSUE TITLE
Higher CPU usage on "Jellyfin Sync" task

### ISSUE THREAD

**Issue by Pabsilon** [CyferShepard/Jellystat#96]
Hi! First off, great job with this app, it's getting better!

I'm running jellystat on docker, and I'm currently running version 1.0.8.
Ever since the update that was released on the 7th (or 6th?), which I can't pin point on docker hub, I've noticed some abnormal CPU use on my server and 10 minutes intervals. Nothing serious, but there is an obvious correlation with updating the jellystat container, To the best of my knowledge, this corresponds with the Jellyfin Sync task on jellystat.

I have 4 Libraries in jellyfin, and the jobs running every 10 minutes have the same trace. These are 10 minutes apart, and no new elements were added to the library or removed. I don't have logs prior to the issue.

<html>
<body>

Name | Type | Date Created | Duration | Execution Type | Result
-- | -- | -- | -- | -- | --
 Jellyfin Sync | Task | 11/10/2023, 13:22:21 | 54 seconds | Automatic | SUCCESS

</body>
</html>

> Syncing... 1/4
> Beginning Library Item Sync
> 0 Rows Inserted. 1008 Rows Updated.
> 0 Library Items Removed.
> Item Sync Complete
> Syncing... 2/4
> Beginning Seasons and Episode sync
> Seasons: 0 Rows Inserted. 503 Rows Updated.
> 0 Seasons Removed.
> Episodes: 249 Rows Inserted. 6921 Rows Updated.
> 6 Episodes Removed.
> Sync Complete
> Syncing... 3/4
> Beginning File Info Sync
> 6 Item Info inserted. 809 Item Info Updated
> 0 Item Info Removed.
> 28 Episodes Info inserted. 6074 Episodes Info Updated
> 0 Episodes Info Removed.
> Info Sync Complete
> Syncing... 4/4
> Removing Orphaned FileInfo/Episode/Season Records
> Orphaned FileInfo/Episode/Season Removed.
> Sync Complete
> Updating Library Stats
> Library Stats Updated.

<html>
<body>

Name | Type | Date Created | Duration | Execution Type | Result
-- | -- | -- | -- | -- | --
Jellyfin Sync | Task | 11/10/2023, 13:12:16 | 54 seconds | Automatic | SUCCESS

</body>
</html>

> Syncing... 1/4
> Beginning Library Item Sync
> 0 Rows Inserted. 1008 Rows Updated.
> 0 Library Items Removed.
> Item Sync Complete
> Syncing... 2/4
> Beginning Seasons and Episode sync
> Seasons: 0 Rows Inserted. 503 Rows Updated.
> 0 Seasons Removed.
> Episodes: 249 Rows Inserted. 6921 Rows Updated.
> 6 Episodes Removed.
> Sync Complete
> Syncing... 3/4
> Beginning File Info Sync
> 6 Item Info inserted. 809 Item Info Updated
> 0 Item Info Removed.
> 28 Episodes Info inserted. 6074 Episodes Info Updated
> 0 Episodes Info Removed.
> Info Sync Complete
> Syncing... 4/4
> Removing Orphaned FileInfo/Episode/Season Records
> Orphaned FileInfo/Episode/Season Removed.
> Sync Complete
> Updating Library Stats
> Library Stats Updated.

**Comment by CyferShepard** [comment]
Hi @Pabsilon ,sorry it took so long to look at this issue, this is actually being looked at under #66 , il close this task as its a derivative of that issue
