### ISSUE TITLE
SIMKL Support

### ISSUE THREAD

**Issue by JamsRepos** [CyferShepard/Jellystat#97]
The ability to add SIMKL integration on a per user or all user basis. 

https://simkl.com/

**Comment by LaSylv** [comment]
What would be the point of integrating a tool like this in jellystats ? 

It is already integrated in Jellyfin

**Comment by JamsRepos** [comment]
> What would be the point of integrating a tool like this in jellystats ?
> 
> It is already integrated in Jellyfin

The ability to add all users history to one SIMKL account as apposed to manually having to link to each indivudual user. Also, the plugin has not received any updates in a while, this issue can be renamed to Webhook Support anyways as that would cover this basis.
