### ISSUE TITLE
Jellyfin sync fails

### ISSUE THREAD

**Issue by kaysond** [CyferShepard/Jellystat#98]
I get the following error:

```
Syncing... 1/4

Beginning Library Item Sync

391 Library Items Removed.

Item Sync Complete

Syncing... 2/4

Beginning Seasons and Episode sync

Seasons: 0 Rows Inserted. 0 Rows Updated.

0 Seasons Removed.

Episodes: 0 Rows Inserted. 0 Rows Updated.

0 Episodes Removed.

Sync Complete

Syncing... 3/4

Beginning File Info Sync

Error Getting AdminId: AxiosError: Request failed with status code 503

at syncItemInfo (/app/backend/routes/sync.js:541:28: Error: TypeError: Cannot read properties of undefined (reading 'Id')

Syncing... 4/4

Removing Orphaned FileInfo/Episode/Season Records

Orphaned FileInfo/Episode/Season Removed.

Sync Complete

Updating Library Stats

Library Stats Updated.
```

**Comment by DaftFuzz** [comment]
Have you definitely got at least one admin user in Jellyfish (Allow this user to manage the server)?

**Comment by kaysond** [comment]
Yes:
![image](https://github.com/CyferShepard/Jellystat/assets/1147328/00ac63a4-0418-464b-8d04-cdea9f3e2144)

**Comment by CyferShepard** [comment]
can you try selecting this admin under the preferred admin section in jellystat?

**Comment by kaysond** [comment]
I selected it and tried the sync again but still getting the error. Is there a way to see what http request was made?

**Comment by CyferShepard** [comment]
so you can check either in the web console or in dockers logs but at that point of the sync it should be calling the ```/Users``` endpoint

**Comment by kaysond** [comment]
hmm it was actually 503-ing which means my reverse proxy didn't get a response from jellyfin. But I'm not seeing any errors in jellyfin at all. I wonder if it just timed out on one of the API calls from the sync...

Are you doing requests in parallel?

In any case, it seems to have run successfully now so I'll close this
